INSERT INTO `definite_cities_provinces` 
(`province_name`, `province_slug`, `created_at`, `updated_at`) 
VALUES 
('Bali', 'bali', NOW(), NOW()),
('Bangka Belitung', 'bangka-belitung', NOW(), NOW()),
('Banten', 'banten', NOW(), NOW()),
('Bengkulu', 'bengkulu', NOW(), NOW()),
('DI Yogyakarta', 'di-yogyakarta', NOW(), NOW()),
('DKI Jakarta', 'dki-jakarta', NOW(), NOW()),
('Gorontalo', 'gorontalo', NOW(), NOW()),
('Jambi', 'jambi', NOW(), NOW()),
('Jawa Barat', 'jawa-barat', NOW(), NOW()),
('Jawa Tengah', 'jawa-tengah', NOW(), NOW()),
('Jawa Timur', 'jawa-timur', NOW(), NOW()),
('Kalimantan Barat', 'kalimantan-barat', NOW(), NOW()),
('Kalimantan Selatan', 'kalimantan-selatan', NOW(), NOW()),
('Kalimantan Tengah', 'kalimantan-tengah', NOW(), NOW()),
('Kalimantan Timur', 'kalimantan-timur', NOW(), NOW()),
('Kalimantan Utara', 'kalimantan-utara', NOW(), NOW()),
('Kepulauan Riau', 'kepulauan-riau', NOW(), NOW()),
('Lampung', 'lampung', NOW(), NOW()),
('Maluku', 'maluku', NOW(), NOW()),
('Maluku Utara', 'maluku-utara', NOW(), NOW()),
('Nanggroe Aceh Darussalam (NAD)', 'nanggroe-aceh-darussalam-nad', NOW(), NOW()),
('Nusa Tenggara Barat (NTB)', 'nusa-tenggara-barat-ntb', NOW(), NOW()),
('Nusa Tenggara Timur (NTT)', 'nusa-tenggara-timur-ntt', NOW(), NOW()),
('Papua', 'papua', NOW(), NOW()),
('Papua Barat', 'papua-barat', NOW(), NOW()),
('Riau', 'riau', NOW(), NOW()),
('Sulawesi Barat', 'sulawesi-barat', NOW(), NOW()),
('Sulawesi Selatan', 'sulawesi-selatan', NOW(), NOW()),
('Sulawesi Tengah', 'sulawesi-tengah', NOW(), NOW()),
('Sulawesi Tenggara', 'sulawesi-tenggara', NOW(), NOW()),
('Sulawesi Utara', 'sulawesi-utara', NOW(), NOW()),
('Sumatera Barat', 'sumatera-barat', NOW(), NOW()),
('Sumatera Selatan', 'sumatera-selatan', NOW(), NOW()),
('Sumatera Utara', 'sumatera-utara', NOW(), NOW());
