INSERT INTO `definite_cities_cities` 
(`province_id`,`city_name`, `city_slug`, `created_at`, `updated_at`) 
VALUES 
('1','Kabupaten Gianyar','kabupaten-gianyar',NOW(),NOW()),
('1','Kabupaten Bangli','kabupaten-bangli',NOW(),NOW()),
('1','Kabupaten Buleleng','kabupaten-buleleng',NOW(),NOW()),
('1','Kabupaten Tabanan','kabupaten-tabanan',NOW(),NOW()),
('1','Kabupaten Karangasem','kabupaten-karangasem',NOW(),NOW()),
('1','Kabupaten Badung','kabupaten-badung',NOW(),NOW()),
('1','Kabupaten Jembrana','kabupaten-jembrana',NOW(),NOW()),
('1','Kabupaten Klungkung','kabupaten-klungkung',NOW(),NOW()),
('1','Kota Denpasar','kota-denpasar',NOW(),NOW()),
('2','Kabupaten Bangka Selatan','kabupaten-bangka-selatan',NOW(),NOW()),
('2','Kabupaten Bangka Barat','kabupaten-bangka-barat',NOW(),NOW()),
('2','Kabupaten Belitung','kabupaten-belitung',NOW(),NOW()),
('2','Kota Pangkal Pinang','kota-pangkal-pinang',NOW(),NOW()),
('2','Kabupaten Bangka Tengah','kabupaten-bangka-tengah',NOW(),NOW()),
('2','Kabupaten Bangka','kabupaten-bangka',NOW(),NOW()),
('2','Kabupaten Belitung Timur','kabupaten-belitung-timur',NOW(),NOW()),
('3','Kabupaten Lebak','kabupaten-lebak',NOW(),NOW()),
('3','Kabupaten Serang','kabupaten-serang',NOW(),NOW()),
('3','Kota Serang','kota-serang',NOW(),NOW()),
('3','Kabupaten Tangerang','kabupaten-tangerang',NOW(),NOW()),
('3','Kota Tangerang','kota-tangerang',NOW(),NOW()),
('3','Kabupaten Pandeglang','kabupaten-pandeglang',NOW(),NOW()),
('3','Kota Tangerang Selatan','kota-tangerang-selatan',NOW(),NOW()),
('3','Kota Cilegon','kota-cilegon',NOW(),NOW()),
('4','Kabupaten Seluma','kabupaten-seluma',NOW(),NOW()),
('4','Kabupaten Bengkulu Tengah','kabupaten-bengkulu-tengah',NOW(),NOW()),
('4','Kota Bengkulu','kota-bengkulu',NOW(),NOW()),
('4','Kabupaten Muko Muko','kabupaten-muko-muko',NOW(),NOW()),
('4','Kabupaten Rejang Lebong','kabupaten-rejang-lebong',NOW(),NOW()),
('4','Kabupaten Kaur','kabupaten-kaur',NOW(),NOW()),
('4','Kabupaten Bengkulu Selatan','kabupaten-bengkulu-selatan',NOW(),NOW()),
('4','Kabupaten Kepahiang','kabupaten-kepahiang',NOW(),NOW()),
('4','Kabupaten Lebong','kabupaten-lebong',NOW(),NOW()),
('4','Kabupaten Bengkulu Utara','kabupaten-bengkulu-utara',NOW(),NOW()),
('5','Kabupaten Gunung Kidul','kabupaten-gunung-kidul',NOW(),NOW()),
('5','Kota Yogyakarta','kota-yogyakarta',NOW(),NOW()),
('5','Kabupaten Kulon Progo','kabupaten-kulon-progo',NOW(),NOW()),
('5','Kabupaten Sleman','kabupaten-sleman',NOW(),NOW()),
('5','Kabupaten Bantul','kabupaten-bantul',NOW(),NOW()),
('6','Kota Jakarta Selatan','kota-jakarta-selatan',NOW(),NOW()),
('6','Kota Jakarta Utara','kota-jakarta-utara',NOW(),NOW()),
('6','Kota Jakarta Pusat','kota-jakarta-pusat',NOW(),NOW()),
('6','Kota Jakarta Barat','kota-jakarta-barat',NOW(),NOW()),
('6','Kota Jakarta Timur','kota-jakarta-timur',NOW(),NOW()),
('6','Kabupaten Kepulauan Seribu','kabupaten-kepulauan-seribu',NOW(),NOW()),
('7','Kabupaten Boalemo','kabupaten-boalemo',NOW(),NOW()),
('7','Kabupaten Pohuwato','kabupaten-pohuwato',NOW(),NOW()),
('7','Kabupaten Gorontalo Utara','kabupaten-gorontalo-utara',NOW(),NOW()),
('7','Kabupaten Gorontalo','kabupaten-gorontalo',NOW(),NOW()),
('7','Kabupaten Bone Bolango','kabupaten-bone-bolango',NOW(),NOW()),
('7','Kota Gorontalo','kota-gorontalo',NOW(),NOW()),
('8','Kabupaten Tebo','kabupaten-tebo',NOW(),NOW()),
('8','Kabupaten Tanjung Jabung Barat','kabupaten-tanjung-jabung-barat',NOW(),NOW()),
('8','Kabupaten Merangin','kabupaten-merangin',NOW(),NOW()),
('8','Kota Jambi','kota-jambi',NOW(),NOW()),
('8','Kabupaten Bungo','kabupaten-bungo',NOW(),NOW()),
('8','Kota Sungaipenuh','kota-sungaipenuh',NOW(),NOW()),
('8','Kabupaten Muaro Jambi','kabupaten-muaro-jambi',NOW(),NOW()),
('8','Kabupaten Kerinci','kabupaten-kerinci',NOW(),NOW()),
('8','Kabupaten Sarolangun','kabupaten-sarolangun',NOW(),NOW()),
('8','Kabupaten Tanjung Jabung Timur','kabupaten-tanjung-jabung-timur',NOW(),NOW()),
('8','Kabupaten Batang Hari','kabupaten-batang-hari',NOW(),NOW()),
('9','Kabupaten Indramayu','kabupaten-indramayu',NOW(),NOW()),
('9','Kabupaten Cirebon','kabupaten-cirebon',NOW(),NOW()),
('9','Kabupaten Cianjur','kabupaten-cianjur',NOW(),NOW()),
('9','Kabupaten Sukabumi','kabupaten-sukabumi',NOW(),NOW()),
('9','Kota Sukabumi','kota-sukabumi',NOW(),NOW()),
('9','Kabupaten Purwakarta','kabupaten-purwakarta',NOW(),NOW()),
('9','Kabupaten Garut','kabupaten-garut',NOW(),NOW()),
('9','Kabupaten Sumedang','kabupaten-sumedang',NOW(),NOW()),
('9','Kota Bandung','kota-bandung',NOW(),NOW()),
('9','Kabupaten Karawang','kabupaten-karawang',NOW(),NOW()),
('9','Kabupaten Bogor','kabupaten-bogor',NOW(),NOW()),
('9','Kota Tasikmalaya','kota-tasikmalaya',NOW(),NOW()),
('9','Kabupaten Bekasi','kabupaten-bekasi',NOW(),NOW()),
('9','Kabupaten Tasikmalaya','kabupaten-tasikmalaya',NOW(),NOW()),
('9','Kota Depok','kota-depok',NOW(),NOW()),
('9','Kabupaten Subang','kabupaten-subang',NOW(),NOW()),
('9','Kota Bogor','kota-bogor',NOW(),NOW()),
('9','Kabupaten Ciamis','kabupaten-ciamis',NOW(),NOW()),
('9','Kabupaten Majalengka','kabupaten-majalengka',NOW(),NOW()),
('9','Kabupaten Kuningan','kabupaten-kuningan',NOW(),NOW()),
('9','Kabupaten Bandung','kabupaten-bandung',NOW(),NOW()),
('9','Kabupaten Bandung Barat','kabupaten-bandung-barat',NOW(),NOW()),
('9','Kabupaten Pangandaran','kabupaten-pangandaran',NOW(),NOW()),
('9','Kota Bekasi','kota-bekasi',NOW(),NOW()),
('9','Kota Banjar','kota-banjar',NOW(),NOW()),
('9','Kota Cirebon','kota-cirebon',NOW(),NOW()),
('9','Kota Cimahi','kota-cimahi',NOW(),NOW()),
('10','Kabupaten Wonogiri','kabupaten-wonogiri',NOW(),NOW()),
('10','Kabupaten Batang','kabupaten-batang',NOW(),NOW()),
('10','Kabupaten Wonosobo','kabupaten-wonosobo',NOW(),NOW()),
('10','Kabupaten Boyolali','kabupaten-boyolali',NOW(),NOW()),
('10','Kabupaten Klaten','kabupaten-klaten',NOW(),NOW()),
('10','Kabupaten Demak','kabupaten-demak',NOW(),NOW()),
('10','Kabupaten Pekalongan','kabupaten-pekalongan',NOW(),NOW()),
('10','Kabupaten Temanggung','kabupaten-temanggung',NOW(),NOW()),
('10','Kabupaten Grobogan','kabupaten-grobogan',NOW(),NOW()),
('10','Kabupaten Pati','kabupaten-pati',NOW(),NOW()),
('10','Kabupaten Magelang','kabupaten-magelang',NOW(),NOW()),
('10','Kabupaten Sukoharjo','kabupaten-sukoharjo',NOW(),NOW()),
('10','Kabupaten Kendal','kabupaten-kendal',NOW(),NOW()),
('10','Kabupaten Jepara','kabupaten-jepara',NOW(),NOW()),
('10','Kabupaten Pemalang','kabupaten-pemalang',NOW(),NOW()),
('10','Kabupaten Tegal','kabupaten-tegal',NOW(),NOW()),
('10','Kabupaten Banyumas','kabupaten-banyumas',NOW(),NOW()),
('10','Kabupaten Banjarnegara','kabupaten-banjarnegara',NOW(),NOW()),
('10','Kabupaten Brebes','kabupaten-brebes',NOW(),NOW()),
('10','Kabupaten Cilacap','kabupaten-cilacap',NOW(),NOW()),
('10','Kabupaten Semarang','kabupaten-semarang',NOW(),NOW()),
('10','Kabupaten Kudus','kabupaten-kudus',NOW(),NOW()),
('10','Kabupaten Blora','kabupaten-blora',NOW(),NOW()),
('10','Kota Semarang','kota-semarang',NOW(),NOW()),
('10','Kota Salatiga','kota-salatiga',NOW(),NOW()),
('10','Kota Tegal','kota-tegal',NOW(),NOW()),
('10','Kabupaten Karanganyar','kabupaten-karanganyar',NOW(),NOW()),
('10','Kabupaten Sragen','kabupaten-sragen',NOW(),NOW()),
('10','Kabupaten Rembang','kabupaten-rembang',NOW(),NOW()),
('10','Kabupaten Kebumen','kabupaten-kebumen',NOW(),NOW()),
('10','Kota Surakarta','kota-surakarta',NOW(),NOW()),
('10','Kabupaten Purbalingga','kabupaten-purbalingga',NOW(),NOW()),
('10','Kabupaten Purworejo','kabupaten-purworejo',NOW(),NOW()),
('10','Kota Pekalongan','kota-pekalongan',NOW(),NOW()),
('10','Kota Magelang','kota-magelang',NOW(),NOW()),
('11','Kabupaten Bangkalan','kabupaten-bangkalan',NOW(),NOW()),
('11','Kabupaten Banyuwangi','kabupaten-banyuwangi',NOW(),NOW()),
('11','Kota Batu','kota-batu',NOW(),NOW()),
('11','Kota Blitar','kota-blitar',NOW(),NOW()),
('11','Kabupaten Blitar','kabupaten-blitar',NOW(),NOW()),
('11','Kabupaten Bojonegoro','kabupaten-bojonegoro',NOW(),NOW()),
('11','Kabupaten Bondowoso','kabupaten-bondowoso',NOW(),NOW()),
('11','Kabupaten Gresik','kabupaten-gresik',NOW(),NOW()),
('11','Kabupaten Jember','kabupaten-jember',NOW(),NOW()),
('11','Kabupaten Jombang','kabupaten-jombang',NOW(),NOW()),
('11','Kota Kediri','kota-kediri',NOW(),NOW()),
('11','Kabupaten Kediri','kabupaten-kediri',NOW(),NOW()),
('11','Kabupaten Lamongan','kabupaten-lamongan',NOW(),NOW()),
('11','Kabupaten Lumajang','kabupaten-lumajang',NOW(),NOW()),
('11','Kota Madiun','kota-madiun',NOW(),NOW()),
('11','Kabupaten Madiun','kabupaten-madiun',NOW(),NOW()),
('11','Kabupaten Magetan','kabupaten-magetan',NOW(),NOW()),
('11','Kota Malang','kota-malang',NOW(),NOW()),
('11','Kabupaten Malang','kabupaten-malang',NOW(),NOW()),
('11','Kota Mojokerto','kota-mojokerto',NOW(),NOW()),
('11','Kabupaten Mojokerto','kabupaten-mojokerto',NOW(),NOW()),
('11','Kabupaten Nganjuk','kabupaten-nganjuk',NOW(),NOW()),
('11','Kabupaten Ngawi','kabupaten-ngawi',NOW(),NOW()),
('11','Kabupaten Pacitan','kabupaten-pacitan',NOW(),NOW()),
('11','Kabupaten Pamekasan','kabupaten-pamekasan',NOW(),NOW()),
('11','Kota Pasuruan','kota-pasuruan',NOW(),NOW()),
('11','Kabupaten Pasuruan','kabupaten-pasuruan',NOW(),NOW()),
('11','Kabupaten Ponorogo','kabupaten-ponorogo',NOW(),NOW()),
('11','Kota Probolinggo','kota-probolinggo',NOW(),NOW()),
('11','Kabupaten Probolinggo','kabupaten-probolinggo',NOW(),NOW()),
('11','Kabupaten Sampang','kabupaten-sampang',NOW(),NOW()),
('11','Kabupaten Sidoarjo','kabupaten-sidoarjo',NOW(),NOW()),
('11','Kabupaten Situbondo','kabupaten-situbondo',NOW(),NOW()),
('11','Kabupaten Sumenep','kabupaten-sumenep',NOW(),NOW()),
('11','Kota Surabaya','kota-surabaya',NOW(),NOW()),
('11','Kabupaten Trenggalek','kabupaten-trenggalek',NOW(),NOW()),
('11','Kabupaten Tuban','kabupaten-tuban',NOW(),NOW()),
('11','Kabupaten Tulungagung','kabupaten-tulungagung',NOW(),NOW()),
('12','Kabupaten Bengkayang','kabupaten-bengkayang',NOW(),NOW()),
('12','Kabupaten Kapuas Hulu','kabupaten-kapuas-hulu',NOW(),NOW()),
('12','Kabupaten Kayong Utara','kabupaten-kayong-utara',NOW(),NOW()),
('12','Kabupaten Ketapang','kabupaten-ketapang',NOW(),NOW()),
('12','Kabupaten Kubu Raya','kabupaten-kubu-raya',NOW(),NOW()),
('12','Kabupaten Landak','kabupaten-landak',NOW(),NOW()),
('12','Kabupaten Melawi','kabupaten-melawi',NOW(),NOW()),
('12','Kabupaten Mempawah','kabupaten-mempawah',NOW(),NOW()),
('12','Kota Pontianak','kota-pontianak',NOW(),NOW()),
('12','Kabupaten Sambas','kabupaten-sambas',NOW(),NOW()),
('12','Kabupaten Sanggau','kabupaten-sanggau',NOW(),NOW()),
('12','Kabupaten Sekadau','kabupaten-sekadau',NOW(),NOW()),
('12','Kota Singkawang','kota-singkawang',NOW(),NOW()),
('12','Kabupaten Sintang','kabupaten-sintang',NOW(),NOW()),
('13','Kabupaten Balangan','kabupaten-balangan',NOW(),NOW()),
('13','Kabupaten Banjar','kabupaten-banjar',NOW(),NOW()),
('13','Kota Banjarbaru','kota-banjarbaru',NOW(),NOW()),
('13','Kota Banjarmasin','kota-banjarmasin',NOW(),NOW()),
('13','Kabupaten Barito Kuala','kabupaten-barito-kuala',NOW(),NOW()),
('13','Kabupaten Hulu Sungai Selatan','kabupaten-hulu-sungai-selatan',NOW(),NOW()),
('13','Kabupaten Hulu Sungai Tengah','kabupaten-hulu-sungai-tengah',NOW(),NOW()),
('13','Kabupaten Hulu Sungai Utara','kabupaten-hulu-sungai-utara',NOW(),NOW()),
('13','Kabupaten Kotabaru','kabupaten-kotabaru',NOW(),NOW()),
('13','Kabupaten Tabalong','kabupaten-tabalong',NOW(),NOW()),
('13','Kabupaten Tanah Bumbu','kabupaten-tanah-bumbu',NOW(),NOW()),
('13','Kabupaten Tanah Laut','kabupaten-tanah-laut',NOW(),NOW()),
('13','Kabupaten Tapin','kabupaten-tapin',NOW(),NOW()),
('14','Kabupaten Barito Selatan','kabupaten-barito-selatan',NOW(),NOW()),
('14','Kabupaten Barito Timur','kabupaten-barito-timur',NOW(),NOW()),
('14','Kabupaten Barito Utara','kabupaten-barito-utara',NOW(),NOW()),
('14','Kabupaten Gunung Mas','kabupaten-gunung-mas',NOW(),NOW()),
('14','Kabupaten Kapuas','kabupaten-kapuas',NOW(),NOW()),
('14','Kabupaten Katingan','kabupaten-katingan',NOW(),NOW()),
('14','Kabupaten Kotawaringin Barat','kabupaten-kotawaringin-barat',NOW(),NOW()),
('14','Kabupaten Kotawaringin Timur','kabupaten-kotawaringin-timur',NOW(),NOW()),
('14','Kabupaten Lamandau','kabupaten-lamandau',NOW(),NOW()),
('14','Kabupaten Murung Raya','kabupaten-murung-raya',NOW(),NOW()),
('14','Kota Palangka Raya','kota-palangka-raya',NOW(),NOW()),
('14','Kabupaten Pulang Pisau','kabupaten-pulang-pisau',NOW(),NOW()),
('14','Kabupaten Seruyan','kabupaten-seruyan',NOW(),NOW()),
('14','Kabupaten Sukamara','kabupaten-sukamara',NOW(),NOW()),
('15','Kota Balikpapan','kota-balikpapan',NOW(),NOW()),
('15','Kabupaten Berau','kabupaten-berau',NOW(),NOW()),
('15','Kota Bontang','kota-bontang',NOW(),NOW()),
('15','Kabupaten Kutai Barat','kabupaten-kutai-barat',NOW(),NOW()),
('15','Kabupaten Kutai Kartanegara','kabupaten-kutai-kartanegara',NOW(),NOW()),
('15','Kabupaten Kutai Timur','kabupaten-kutai-timur',NOW(),NOW()),
('15','Kabupaten Mahakam Ulu','kabupaten-mahakam-ulu',NOW(),NOW()),
('15','Kabupaten Paser','kabupaten-paser',NOW(),NOW()),
('15','Kabupaten Penajam Paser Utara','kabupaten-penajam-paser-utara',NOW(),NOW()),
('15','Kota Samarinda','kota-samarinda',NOW(),NOW()),
('16','Kabupaten Bulungan','kabupaten-bulungan',NOW(),NOW()),
('16','Kabupaten Malinau','kabupaten-malinau',NOW(),NOW()),
('16','Kabupaten Nunukan','kabupaten-nunukan',NOW(),NOW()),
('16','Kabupaten Tana Tidung','kabupaten-tana-tidung',NOW(),NOW()),
('16','Kota Tarakan','kota-tarakan',NOW(),NOW()),
('17','Kota Batam','kota-batam',NOW(),NOW()),
('17','Kabupaten Bintan','kabupaten-bintan',NOW(),NOW()),
('17','Kabupaten Karimun','kabupaten-karimun',NOW(),NOW()),
('17','Kabupaten Kepulauan Anambas','kabupaten-kepulauan-anambas',NOW(),NOW()),
('17','Kabupaten Lingga','kabupaten-lingga',NOW(),NOW()),
('17','Kabupaten Natuna','kabupaten-natuna',NOW(),NOW()),
('17','Kota Tanjung Pinang','kota-tanjung-pinang',NOW(),NOW()),
('18','Kota Bandar Lampung','kota-bandar-lampung',NOW(),NOW()),
('18','Kabupaten Lampung Barat','kabupaten-lampung-barat',NOW(),NOW()),
('18','Kabupaten Lampung Selatan','kabupaten-lampung-selatan',NOW(),NOW()),
('18','Kabupaten Lampung Tengah','kabupaten-lampung-tengah',NOW(),NOW()),
('18','Kabupaten Lampung Timur','kabupaten-lampung-timur',NOW(),NOW()),
('18','Kabupaten Lampung Utara','kabupaten-lampung-utara',NOW(),NOW()),
('18','Kabupaten Mesuji','kabupaten-mesuji',NOW(),NOW()),
('18','Kota Metro','kota-metro',NOW(),NOW()),
('18','Kabupaten Pesawaran','kabupaten-pesawaran',NOW(),NOW()),
('18','Kabupaten Pesisir Barat','kabupaten-pesisir-barat',NOW(),NOW()),
('18','Kabupaten Pringsewu','kabupaten-pringsewu',NOW(),NOW()),
('18','Kabupaten Tanggamus','kabupaten-tanggamus',NOW(),NOW()),
('18','Kabupaten Tulang Bawang','kabupaten-tulang-bawang',NOW(),NOW()),
('18','Kabupaten Tulang Bawang Barat','kabupaten-tulang-bawang-barat',NOW(),NOW()),
('18','Kabupaten Way Kanan','kabupaten-way-kanan',NOW(),NOW()),
('19','Kota Ambon','kota-ambon',NOW(),NOW()),
('19','Kabupaten Buru','kabupaten-buru',NOW(),NOW()),
('19','Kabupaten Buru Selatan','kabupaten-buru-selatan',NOW(),NOW()),
('19','Kabupaten Kepulauan Aru','kabupaten-kepulauan-aru',NOW(),NOW()),
('19','Kabupaten Maluku Barat Daya','kabupaten-maluku-barat-daya',NOW(),NOW()),
('19','Kabupaten Maluku Tengah','kabupaten-maluku-tengah',NOW(),NOW()),
('19','Kabupaten Maluku Tenggara','kabupaten-maluku-tenggara',NOW(),NOW()),
('19','Kabupaten Maluku Tenggara Barat','kabupaten-maluku-tenggara-barat',NOW(),NOW()),
('19','Kabupaten Seram Bagian Barat','kabupaten-seram-bagian-barat',NOW(),NOW()),
('19','Kabupaten Seram Bagian Timur','kabupaten-seram-bagian-timur',NOW(),NOW()),
('19','Kota Tual','kota-tual',NOW(),NOW()),
('20','Kabupaten Halmahera Barat','kabupaten-halmahera-barat',NOW(),NOW()),
('20','Kabupaten Halmahera Selatan','kabupaten-halmahera-selatan',NOW(),NOW()),
('20','Kabupaten Halmahera Tengah','kabupaten-halmahera-tengah',NOW(),NOW()),
('20','Kabupaten Halmahera Timur','kabupaten-halmahera-timur',NOW(),NOW()),
('20','Kabupaten Halmahera Utara','kabupaten-halmahera-utara',NOW(),NOW()),
('20','Kabupaten Kepulauan Sula','kabupaten-kepulauan-sula',NOW(),NOW()),
('20','Kabupaten Pulau Morotai','kabupaten-pulau-morotai',NOW(),NOW()),
('20','Kabupaten Pulau Taliabu','kabupaten-pulau-taliabu',NOW(),NOW()),
('20','Kota Ternate','kota-ternate',NOW(),NOW()),
('20','Kota Tidore Kepulauan','kota-tidore-kepulauan',NOW(),NOW()),
('21','Kabupaten Aceh Barat','kabupaten-aceh-barat',NOW(),NOW()),
('21','Kabupaten Aceh Barat Daya','kabupaten-aceh-barat-daya',NOW(),NOW()),
('21','Kabupaten Aceh Besar','kabupaten-aceh-besar',NOW(),NOW()),
('21','Kabupaten Aceh Jaya','kabupaten-aceh-jaya',NOW(),NOW()),
('21','Kabupaten Aceh Selatan','kabupaten-aceh-selatan',NOW(),NOW()),
('21','Kabupaten Aceh Singkil','kabupaten-aceh-singkil',NOW(),NOW()),
('21','Kabupaten Aceh Tamiang','kabupaten-aceh-tamiang',NOW(),NOW()),
('21','Kabupaten Aceh Tengah','kabupaten-aceh-tengah',NOW(),NOW()),
('21','Kabupaten Aceh Tenggara','kabupaten-aceh-tenggara',NOW(),NOW()),
('21','Kabupaten Aceh Timur','kabupaten-aceh-timur',NOW(),NOW()),
('21','Kabupaten Aceh Utara','kabupaten-aceh-utara',NOW(),NOW()),
('21','Kota Banda Aceh','kota-banda-aceh',NOW(),NOW()),
('21','Kabupaten Bener Meriah','kabupaten-bener-meriah',NOW(),NOW()),
('21','Kabupaten Bireuen','kabupaten-bireuen',NOW(),NOW()),
('21','Kabupaten Gayo Lues','kabupaten-gayo-lues',NOW(),NOW()),
('21','Kota Lhokseumawe','kota-lhokseumawe',NOW(),NOW()),
('21','Kabupaten Nagan Raya','kabupaten-nagan-raya',NOW(),NOW()),
('21','Kabupaten Pidie','kabupaten-pidie',NOW(),NOW()),
('21','Kabupaten Pidie Jaya','kabupaten-pidie-jaya',NOW(),NOW()),
('21','Kota Sabang','kota-sabang',NOW(),NOW()),
('21','Kabupaten Simeulue','kabupaten-simeulue',NOW(),NOW()),
('21','Kota Subulussalam','kota-subulussalam',NOW(),NOW()),
('22','Kota Bima','kota-bima',NOW(),NOW()),
('22','Kabupaten Bima','kabupaten-bima',NOW(),NOW()),
('22','Kabupaten Dompu','kabupaten-dompu',NOW(),NOW()),
('22','Kabupaten Lombok Barat','kabupaten-lombok-barat',NOW(),NOW()),
('22','Kabupaten Lombok Tengah','kabupaten-lombok-tengah',NOW(),NOW()),
('22','Kabupaten Lombok Timur','kabupaten-lombok-timur',NOW(),NOW()),
('22','Kabupaten Lombok Utara','kabupaten-lombok-utara',NOW(),NOW()),
('22','Kota Mataram','kota-mataram',NOW(),NOW()),
('22','Kabupaten Sumbawa','kabupaten-sumbawa',NOW(),NOW()),
('22','Kabupaten Sumbawa Barat','kabupaten-sumbawa-barat',NOW(),NOW()),
('23','Kabupaten Alor','kabupaten-alor',NOW(),NOW()),
('23','Kabupaten Belu','kabupaten-belu',NOW(),NOW()),
('23','Kabupaten Ende','kabupaten-ende',NOW(),NOW()),
('23','Kabupaten  Flores Timur','kabupaten-flores-timur',NOW(),NOW()),
('23','Kota Kupang','kota-kupang',NOW(),NOW()),
('23','Kabupaten Kupang','kabupaten-kupang',NOW(),NOW()),
('23','Kabupaten Lembata','kabupaten-lembata',NOW(),NOW()),
('23','Kabupaten Malaka','kabupaten-malaka',NOW(),NOW()),
('23','Kabupaten Manggarai','kabupaten-manggarai',NOW(),NOW()),
('23','Kabupaten Manggarai Barat','kabupaten-manggarai-barat',NOW(),NOW()),
('23','Kabupaten Manggarai Timur','kabupaten-manggarai-timur',NOW(),NOW()),
('23','Kabupaten Nagekeo','kabupaten-nagekeo',NOW(),NOW()),
('23','Kabupaten Ngada','kabupaten-ngada',NOW(),NOW()),
('23','Kabupaten Rote Ndao','kabupaten-rote-ndao',NOW(),NOW()),
('23','Kabupaten Sabu Raijua','kabupaten-sabu-raijua',NOW(),NOW()),
('23','Kabupaten Sikka','kabupaten-sikka',NOW(),NOW()),
('23','Kabupaten Sumba Barat','kabupaten-sumba-barat',NOW(),NOW()),
('23','Kabupaten Sumba Barat Daya','kabupaten-sumba-barat-daya',NOW(),NOW()),
('23','Kabupaten Sumba Tengah','kabupaten-sumba-tengah',NOW(),NOW()),
('23','Kabupaten Sumba Timur','kabupaten-sumba-timur',NOW(),NOW()),
('23','Kabupaten Timor Tengah Selatan','kabupaten-timor-tengah-selatan',NOW(),NOW()),
('23','Kabupaten Timor Tengah Utara','kabupaten-timor-tengah-utara',NOW(),NOW()),
('24','Kabupaten Asmat','kabupaten-asmat',NOW(),NOW()),
('24','Kabupaten Biak Numfor','kabupaten-biak-numfor',NOW(),NOW()),
('24','Kabupaten Boven Digoel','kabupaten-boven-digoel',NOW(),NOW()),
('24','Kabupaten Deiyai','kabupaten-deiyai',NOW(),NOW()),
('24','Kabupaten Dogiyai','kabupaten-dogiyai',NOW(),NOW()),
('24','Kabupaten Intan Jaya','kabupaten-intan-jaya',NOW(),NOW()),
('24','Kota Jayapura','kota-jayapura',NOW(),NOW()),
('24','Kabupaten Jayapura','kabupaten-jayapura',NOW(),NOW()),
('24','Kabupaten Jayawijaya','kabupaten-jayawijaya',NOW(),NOW()),
('24','Kabupaten Keerom','kabupaten-keerom',NOW(),NOW()),
('24','Kabupaten Kepulauan Yapen','kabupaten-kepulauan-yapen',NOW(),NOW()),
('24','Kabupaten Lanny Jaya','kabupaten-lanny-jaya',NOW(),NOW()),
('24','Kabupaten Mamberamo Raya','kabupaten-mamberamo-raya',NOW(),NOW()),
('24','Kabupaten Mamberamo Tengah','kabupaten-mamberamo-tengah',NOW(),NOW()),
('24','Kabupaten Mappi','kabupaten-mappi',NOW(),NOW()),
('24','Kabupaten Merauke','kabupaten-merauke',NOW(),NOW()),
('24','Kabupaten Mimika','kabupaten-mimika',NOW(),NOW()),
('24','Kabupaten Nabire','kabupaten-nabire',NOW(),NOW()),
('24','Kabupaten Nduga','kabupaten-nduga',NOW(),NOW()),
('24','Kabupaten Paniai','kabupaten-paniai',NOW(),NOW()),
('24','Kabupaten Pegunungan Bintang','kabupaten-pegunungan-bintang',NOW(),NOW()),
('24','Kabupaten Puncak','kabupaten-puncak',NOW(),NOW()),
('24','Kabupaten Puncak Jaya','kabupaten-puncak-jaya',NOW(),NOW()),
('24','Kabupaten Sarmi','kabupaten-sarmi',NOW(),NOW()),
('24','Kabupaten Supiori','kabupaten-supiori',NOW(),NOW()),
('24','Kabupaten Tolikara','kabupaten-tolikara',NOW(),NOW()),
('24','Kabupaten Waropen','kabupaten-waropen',NOW(),NOW()),
('24','Kabupaten Yahukimo','kabupaten-yahukimo',NOW(),NOW()),
('24','Kabupaten Yalimo','kabupaten-yalimo',NOW(),NOW()),
('25','Kabupaten Fakfak','kabupaten-fakfak',NOW(),NOW()),
('25','Kabupaten Kaimana','kabupaten-kaimana',NOW(),NOW()),
('25','Kabupaten Manokwari','kabupaten-manokwari',NOW(),NOW()),
('25','Kabupaten Manokwari Selatan','kabupaten-manokwari-selatan',NOW(),NOW()),
('25','Kabupaten Maybrat','kabupaten-maybrat',NOW(),NOW()),
('25','Kabupaten Pegunungan Arfak','kabupaten-pegunungan-arfak',NOW(),NOW()),
('25','Kabupaten Raja Ampat','kabupaten-raja-ampat',NOW(),NOW()),
('25','Kota Sorong','kota-sorong',NOW(),NOW()),
('25','Kabupaten Sorong','kabupaten-sorong',NOW(),NOW()),
('25','Kabupaten Sorong Selatan','kabupaten-sorong-selatan',NOW(),NOW()),
('25','Kabupaten Tambrauw','kabupaten-tambrauw',NOW(),NOW()),
('25','Kabupaten Teluk Bintuni','kabupaten-teluk-bintuni',NOW(),NOW()),
('25','Kabupaten Teluk Wondama','kabupaten-teluk-wondama',NOW(),NOW()),
('26','Kabupaten Bengkalis','kabupaten-bengkalis',NOW(),NOW()),
('26','Kota Dumai','kota-dumai',NOW(),NOW()),
('26','Kabupaten Indragiri Hilir','kabupaten-indragiri-hilir',NOW(),NOW()),
('26','Kabupaten Indragiri Hulu','kabupaten-indragiri-hulu',NOW(),NOW()),
('26','Kabupaten Kampar','kabupaten-kampar',NOW(),NOW()),
('26','Kabupaten Kepulauan Meranti','kabupaten-kepulauan-meranti',NOW(),NOW()),
('26','Kabupaten Kuantan Singingi','kabupaten-kuantan-singingi',NOW(),NOW()),
('26','Kota Pekanbaru','kota-pekanbaru',NOW(),NOW()),
('26','Kabupaten Pelalawan','kabupaten-pelalawan',NOW(),NOW()),
('26','Kabupaten Rokan Hilir','kabupaten-rokan-hilir',NOW(),NOW()),
('26','Kabupaten Rokan Hulu','kabupaten-rokan-hulu',NOW(),NOW()),
('26','Kabupaten Siak','kabupaten-siak',NOW(),NOW()),
('27','Kabupaten Majene','kabupaten-majene',NOW(),NOW()),
('27','Kabupaten Mamasa','kabupaten-mamasa',NOW(),NOW()),
('27','Kabupaten Mamuju','kabupaten-mamuju',NOW(),NOW()),
('27','Kabupaten Mamuju Tengah','kabupaten-mamuju-tengah',NOW(),NOW()),
('27','Kabupaten Mamuju Utara','kabupaten-mamuju-utara',NOW(),NOW()),
('27','Kabupaten Polewali Mandar','kabupaten-polewali-mandar',NOW(),NOW()),
('28','Kabupaten Bantaeng','kabupaten-bantaeng',NOW(),NOW()),
('28','Kabupaten Barru','kabupaten-barru',NOW(),NOW()),
('28','Kabupaten Bone','kabupaten-bone',NOW(),NOW()),
('28','Kabupaten Bulukumba','kabupaten-bulukumba',NOW(),NOW()),
('28','Kabupaten Enrekang','kabupaten-enrekang',NOW(),NOW()),
('28','Kabupaten Gowa','kabupaten-gowa',NOW(),NOW()),
('28','Kabupaten Jeneponto','kabupaten-jeneponto',NOW(),NOW()),
('28','Kabupaten Kepulauan Selayar','kabupaten-kepulauan-selayar',NOW(),NOW()),
('28','Kabupaten Luwu','kabupaten-luwu',NOW(),NOW()),
('28','Kabupaten Luwu Timur','kabupaten-luwu-timur',NOW(),NOW()),
('28','Kabupaten Luwu Utara','kabupaten-luwu-utara',NOW(),NOW()),
('28','Kota Makassar','kota-makassar',NOW(),NOW()),
('28','Kabupaten Maros','kabupaten-maros',NOW(),NOW()),
('28','Kota Palopo','kota-palopo',NOW(),NOW()),
('28','Kabupaten Pangkajene Kepulauan','kabupaten-pangkajene-kepulauan',NOW(),NOW()),
('28','Kota Parepare','kota-parepare',NOW(),NOW()),
('28','Kabupaten Pinrang','kabupaten-pinrang',NOW(),NOW()),
('28','Kabupaten Sidenreng Rappang','kabupaten-sidenreng-rappang',NOW(),NOW()),
('28','Kabupaten Sinjai','kabupaten-sinjai',NOW(),NOW()),
('28','Kabupaten Soppeng','kabupaten-soppeng',NOW(),NOW()),
('28','Kabupaten Takalar','kabupaten-takalar',NOW(),NOW()),
('28','Kabupaten Tana Toraja','kabupaten-tana-toraja',NOW(),NOW()),
('28','Kabupaten Toraja Utara','kabupaten-toraja-utara',NOW(),NOW()),
('28','Kabupaten Wajo','kabupaten-wajo',NOW(),NOW()),
('29','Kabupaten Banggai','kabupaten-banggai',NOW(),NOW()),
('29','Kabupaten Banggai Kepulauan','kabupaten-banggai-kepulauan',NOW(),NOW()),
('29','Kabupaten Banggai Laut','kabupaten-banggai-laut',NOW(),NOW()),
('29','Kabupaten Buol','kabupaten-buol',NOW(),NOW()),
('29','Kabupaten Donggala','kabupaten-donggala',NOW(),NOW()),
('29','Kabupaten Morowali','kabupaten-morowali',NOW(),NOW()),
('29','Kabupaten Morowali Utara','kabupaten-morowali-utara',NOW(),NOW()),
('29','Kota Palu','kota-palu',NOW(),NOW()),
('29','Kabupaten Parigi Moutong','kabupaten-parigi-moutong',NOW(),NOW()),
('29','Kabupaten Poso','kabupaten-poso',NOW(),NOW()),
('29','Kabupaten Sigi','kabupaten-sigi',NOW(),NOW()),
('29','Kabupaten Tojo Una-Una','kabupaten-tojo-una-una',NOW(),NOW()),
('29','Kabupaten Toli-Toli','kabupaten-toli-toli',NOW(),NOW()),
('30','Kota Bau-Bau','kota-bau-bau',NOW(),NOW()),
('30','Kabupaten Bombana','kabupaten-bombana',NOW(),NOW()),
('30','Kabupaten Buton','kabupaten-buton',NOW(),NOW()),
('30','Kabupaten Buton Selatan','kabupaten-buton-selatan',NOW(),NOW()),
('30','Kabupaten Buton Tengah','kabupaten-buton-tengah',NOW(),NOW()),
('30','Kabupaten Buton Utara','kabupaten-buton-utara',NOW(),NOW()),
('30','Kota Kendari','kota-kendari',NOW(),NOW()),
('30','Kabupaten Kolaka','kabupaten-kolaka',NOW(),NOW()),
('30','Kabupaten Kolaka Timur','kabupaten-kolaka-timur',NOW(),NOW()),
('30','Kabupaten Kolaka Utara','kabupaten-kolaka-utara',NOW(),NOW()),
('30','Kabupaten Konawe','kabupaten-konawe',NOW(),NOW()),
('30','Kabupaten Konawe Kepulauan','kabupaten-konawe-kepulauan',NOW(),NOW()),
('30','Kabupaten Konawe Selatan','kabupaten-konawe-selatan',NOW(),NOW()),
('30','Kabupaten Konawe Utara','kabupaten-konawe-utara',NOW(),NOW()),
('30','Kabupaten Muna','kabupaten-muna',NOW(),NOW()),
('30','Kabupaten Muna Barat','kabupaten-muna-barat',NOW(),NOW()),
('30','Kabupaten Wakatobi','kabupaten-wakatobi',NOW(),NOW()),
('31','Kota Bitung','kota-bitung',NOW(),NOW()),
('31','Kabupaten Bolaang Mongondow','kabupaten-bolaang-mongondow',NOW(),NOW()),
('31','Kabupaten Bolaang Mongondow Selatan','kabupaten-bolaang-mongondow-selatan',NOW(),NOW()),
('31','Kabupaten Bolaang Mongondow Timur','kabupaten-bolaang-mongondow-timur',NOW(),NOW()),
('31','Kabupaten Bolaang Mongondow Utara','kabupaten-bolaang-mongondow-utara',NOW(),NOW()),
('31','Kabupaten Kepulauan Sangihe','kabupaten-kepulauan-sangihe',NOW(),NOW()),
('31','Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)','kabupaten-kepulauan-siau-tagulandang-biaro-sitaro',NOW(),NOW()),
('31','Kabupaten Kepulauan Talaud','kabupaten-kepulauan-talaud',NOW(),NOW()),
('31','Kota Kotamobagu','kota-kotamobagu',NOW(),NOW()),
('31','Kota Manado','kota-manado',NOW(),NOW()),
('31','Kabupaten Minahasa','kabupaten-minahasa',NOW(),NOW()),
('31','Kabupaten Minahasa Selatan','kabupaten-minahasa-selatan',NOW(),NOW()),
('31','Kabupaten Minahasa Tenggara','kabupaten-minahasa-tenggara',NOW(),NOW()),
('31','Kabupaten Minahasa Utara','kabupaten-minahasa-utara',NOW(),NOW()),
('31','Kota Tomohon','kota-tomohon',NOW(),NOW()),
('32','Kabupaten Agam','kabupaten-agam',NOW(),NOW()),
('32','Kota Bukittinggi','kota-bukittinggi',NOW(),NOW()),
('32','Kabupaten Dharmasraya','kabupaten-dharmasraya',NOW(),NOW()),
('32','Kabupaten Kepulauan Mentawai','kabupaten-kepulauan-mentawai',NOW(),NOW()),
('32','Kabupaten Lima Puluh Kota','kabupaten-lima-puluh-kota',NOW(),NOW()),
('32','Kota Padang','kota-padang',NOW(),NOW()),
('32','Kota Padang Panjang','kota-padang-panjang',NOW(),NOW()),
('32','Kabupaten Padang Pariaman','kabupaten-padang-pariaman',NOW(),NOW()),
('32','Kota Pariaman','kota-pariaman',NOW(),NOW()),
('32','Kabupaten Pasaman','kabupaten-pasaman',NOW(),NOW()),
('32','Kabupaten Pasaman Barat','kabupaten-pasaman-barat',NOW(),NOW()),
('32','Kota Payakumbuh','kota-payakumbuh',NOW(),NOW()),
('32','Kabupaten Pesisir Selatan','kabupaten-pesisir-selatan',NOW(),NOW()),
('32','Kota Sawah Lunto','kota-sawah-lunto',NOW(),NOW()),
('32','Kabupaten Sijunjung','kabupaten-sijunjung',NOW(),NOW()),
('32','Kota Solok','kota-solok',NOW(),NOW()),
('32','Kabupaten Solok','kabupaten-solok',NOW(),NOW()),
('32','Kabupaten Solok Selatan','kabupaten-solok-selatan',NOW(),NOW()),
('32','Kabupaten Tanah Datar','kabupaten-tanah-datar',NOW(),NOW()),
('33','Kabupaten Banyuasin','kabupaten-banyuasin',NOW(),NOW()),
('33','Kabupaten Empat Lawang','kabupaten-empat-lawang',NOW(),NOW()),
('33','Kabupaten Lahat','kabupaten-lahat',NOW(),NOW()),
('33','Kota Lubuk Linggau','kota-lubuk-linggau',NOW(),NOW()),
('33','Kabupaten Muara Enim','kabupaten-muara-enim',NOW(),NOW()),
('33','Kabupaten Musi Banyuasin','kabupaten-musi-banyuasin',NOW(),NOW()),
('33','Kabupaten Musi Rawas','kabupaten-musi-rawas',NOW(),NOW()),
('33','Kabupaten Musi Rawas Utara','kabupaten-musi-rawas-utara',NOW(),NOW()),
('33','Kabupaten Ogan Ilir','kabupaten-ogan-ilir',NOW(),NOW()),
('33','Kabupaten Ogan Komering Ilir','kabupaten-ogan-komering-ilir',NOW(),NOW()),
('33','Kabupaten Ogan Komering Ulu','kabupaten-ogan-komering-ulu',NOW(),NOW()),
('33','Kabupaten Ogan Komering Ulu Selatan','kabupaten-ogan-komering-ulu-selatan',NOW(),NOW()),
('33','Kabupaten Ogan Komering Ulu Timur','kabupaten-ogan-komering-ulu-timur',NOW(),NOW()),
('33','Kota Pagar Alam','kota-pagar-alam',NOW(),NOW()),
('33','Kota Palembang','kota-palembang',NOW(),NOW()),
('33','Kabupaten Penukal Abab Lematang Ilir','kabupaten-penukal-abab-lematang-ilir',NOW(),NOW()),
('33','Kota Prabumulih','kota-prabumulih',NOW(),NOW()),
('34','Kabupaten Asahan','kabupaten-asahan',NOW(),NOW()),
('34','Kabupaten Batu Bara','kabupaten-batu-bara',NOW(),NOW()),
('34','Kota Binjai','kota-binjai',NOW(),NOW()),
('34','Kabupaten Dairi','kabupaten-dairi',NOW(),NOW()),
('34','Kabupaten Deli Serdang','kabupaten-deli-serdang',NOW(),NOW()),
('34','Kota Gunungsitoli','kota-gunungsitoli',NOW(),NOW()),
('34','Kabupaten Humbang Hasundutan','kabupaten-humbang-hasundutan',NOW(),NOW()),
('34','Kabupaten Karo','kabupaten-karo',NOW(),NOW()),
('34','Kabupaten Labuhanbatu','kabupaten-labuhanbatu',NOW(),NOW()),
('34','Kabupaten Labuhanbatu Selatan','kabupaten-labuhanbatu-selatan',NOW(),NOW()),
('34','Kabupaten Labuhanbatu Utara','kabupaten-labuhanbatu-utara',NOW(),NOW()),
('34','Kabupaten Langkat','kabupaten-langkat',NOW(),NOW()),
('34','Kabupaten Mandailing Natal','kabupaten-mandailing-natal',NOW(),NOW()),
('34','Kota Medan','kota-medan',NOW(),NOW()),
('34','Kabupaten Nias','kabupaten-nias',NOW(),NOW()),
('34','Kabupaten Nias Barat','kabupaten-nias-barat',NOW(),NOW()),
('34','Kabupaten Nias Selatan','kabupaten-nias-selatan',NOW(),NOW()),
('34','Kabupaten Nias Utara','kabupaten-nias-utara',NOW(),NOW()),
('34','Kabupaten Padang Lawas','kabupaten-padang-lawas',NOW(),NOW()),
('34','Kabupaten Padang Lawas Utara','kabupaten-padang-lawas-utara',NOW(),NOW()),
('34','Kota Padang Sidempuan','kota-padang-sidempuan',NOW(),NOW()),
('34','Kabupaten Pakpak Bharat','kabupaten-pakpak-bharat',NOW(),NOW()),
('34','Kota Pematang Siantar','kota-pematang-siantar',NOW(),NOW()),
('34','Kabupaten Samosir','kabupaten-samosir',NOW(),NOW()),
('34','Kabupaten Serdang Bedagai','kabupaten-serdang-bedagai',NOW(),NOW()),
('34','Kota Sibolga','kota-sibolga',NOW(),NOW()),
('34','Kabupaten Simalungun','kabupaten-simalungun',NOW(),NOW()),
('34','Kota Tanjung Balai','kota-tanjung-balai',NOW(),NOW()),
('34','Kabupaten Tapanuli Selatan','kabupaten-tapanuli-selatan',NOW(),NOW()),
('34','Kabupaten Tapanuli Tengah','kabupaten-tapanuli-tengah',NOW(),NOW()),
('34','Kabupaten Tapanuli Utara','kabupaten-tapanuli-utara',NOW(),NOW()),
('34','Kota Tebing Tinggi','kota-tebing-tinggi',NOW(),NOW()),
('34','Kabupaten Toba Samosir','kabupaten-toba-samosir',NOW(),NOW()),
('3','Tangerang','tangerang',NOW(),NOW()),
('3','Tangerang Selatan','tangerang-selatan',NOW(),NOW()),
('5','Kabupaten Gunungkidul','kabupaten-gunungkidul',NOW(),NOW());
