<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
        version="1.0"
        xmlns:sm="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
        xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
        xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"
        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
        xmlns:fo="http://www.w3.org/1999/XSL/Format"
        xmlns:xhtml="http://www.w3.org/1999/xhtml"
        xmlns="http://www.w3.org/1999/xhtml">

    <xsl:output method="html" indent="yes" encoding="UTF-8"/>

    <xsl:template match="/">
        <html>
            <head>
                <title>
                    <xsl:choose>
                        <xsl:when test="sm:sitemapindex">
                            Frisian Flag | Sitemap Index
                        </xsl:when>
                        <xsl:otherwise>
                           Frisian Flag | XML Sitemap
                        </xsl:otherwise>
                    </xsl:choose>
                </title>
                <style type="text/css">
                    *{margin: 0;padding: 0;}
                    body{color: #333;font-family: Arial;padding: 50px;font-size: 12px;}
                    h1, h3{margin-bottom: 20px; color:#0F4D9A;}
                    h1{font-size: 24px;}
                    h3{font-size: 16px;}
                    h1 span{font-size: 16px;color: #555;margin-left: 5px;}
                    p{line-height: 10px;}
                    table{width:100%;border-collapse: collapse;font-size: 12px;}
                    th, td {
                      padding: 10px;
                      text-align: left;
                    }
                    th {
                      background-color: #009FE3;
                      color: white;
                    }
                    tr:nth-child(odd){background-color: #fcfcfc;}
                    table tbody tr:hover {
                        background-color: #f4fdff;
                    }
                    table tbody tr:hover td, table tbody tr:hover td a {
                        color: #00A6B5;
                    }
                    table, td, th {
                      border: 1px solid #fcfcfc;
                    }
                    .desc{
                        margin-bottom:20px;
                    }
                    .navy{
                        color:#0F4D9A;
                        font-weight:bold;
                        font-size: 16px;
                    }
                    .fs-14{
                        font-size:14px;
                    }
                    a:link, a:visited, .desc {
                      color: #009FE3;
                    }
                   
                </style>
            </head>
            <body>
                <h1>
                    <xsl:choose>
                        <xsl:when test="sm:sitemapindex">
                            Sitemap Index
                        </xsl:when>
                        <xsl:otherwise>
                            XML Sitemap
                        </xsl:otherwise>
                    </xsl:choose>
                </h1>
                <xsl:choose>
                        <xsl:when test="sm:sitemapindex">
                           <p class="desc">Generated by <a class="navy fs-14" href="https://www.frisianflag.com/">Frisian Flag</a> Management System, this is a Sitemap Index, meant to be consumed by search engines like Google or Bing.</p>
                        </xsl:when>
                        <xsl:otherwise>
                           <p class="desc">Generated by <a class="navy fs-14" href="https://www.frisianflag.com/">Frisian Flag</a> Management System, this is an XML Sitemap, meant to be consumed by search engines like Google or Bing.</p>
                        </xsl:otherwise>
                    </xsl:choose>
                
                <p class="desc">You can find more information about XML sitemaps on <a class="navy fs-14" href="https://www.sitemaps.org/index.html" target="_blank">sitemaps.org.</a></p>
                <p class="desc">
                    <xsl:choose>
                        <xsl:when test="sm:sitemapindex">
                            This XML Sitemap Index file contains
                             <span class="navy"><xsl:value-of select="count(sm:sitemapindex/sm:sitemap)"/></span>
                            sitemaps.
                        </xsl:when>
                        <xsl:otherwise>
                            This XML Sitemap contains
                            <span class="navy"><xsl:value-of select="count(sm:urlset/sm:url)"/></span>
                            URLs.
                        </xsl:otherwise>
                    </xsl:choose>
                </p>
                <xsl:apply-templates/>

            </body>
        </html>
    </xsl:template>

    <xsl:template match="sm:sitemapindex">
        <table>
            <tr>
                
                <th>URL</th>
                <th>Last Modified</th>
            </tr>
            <xsl:for-each select="sm:sitemap">
                <tr>
                    <xsl:variable name="loc">
                        <xsl:value-of select="sm:loc"/>
                    </xsl:variable>
                   
                    <td>
                        <a href="{$loc}">
                            <xsl:value-of select="sm:loc"/>
                        </a>
                    </td>
                    <xsl:apply-templates/>
                </tr>
            </xsl:for-each>
        </table>
    </xsl:template>

    <xsl:template match="sm:urlset">
        <table>
            <tr>
               
                <th>URL</th>
                 <xsl:if test="sm:url/sm:priority">
                    <th>Priority</th>
                </xsl:if>
                <xsl:if test="sm:url/sm:changefreq">
                    <th>Change Frequency</th>
                </xsl:if>
                <xsl:if test="sm:url/sm:lastmod">
                    <th>Last Modified</th>
                </xsl:if>
               
            </tr>
            <xsl:for-each select="sm:url">
                <tr>
                    <xsl:variable name="loc">
                        <xsl:value-of select="sm:loc"/>
                    </xsl:variable>
                    <td>
                        <p>
                            <a href="{$loc}">
                                <xsl:value-of select="sm:loc"/>
                            </a>
                        </p>
                    </td>
                    <td class="priority">
                        <xsl:value-of select="concat(sm:priority*100,'%')"/>
                    </td>
                    <xsl:apply-templates select="sm:changefreq"/>
                    <xsl:apply-templates select="sm:lastmod"/>
                </tr>
            </xsl:for-each>
        </table>
    </xsl:template>

    <xsl:template match="sm:loc|image:loc|image:caption|video:*">
    </xsl:template>

    <xsl:template match="sm:priority|sm:changefreq|sm:lastmod">
        <td>
            <xsl:apply-templates/>
        </td>
    </xsl:template>
</xsl:stylesheet>